useEffect(() => {
  setLabels((prev) => ({
    billTo: prev.billTo || t("Bill To"),
    shipTo: prev.shipTo || t("Ship To"),
    date: prev.date || t("Date"),
    paymentTerms: prev.paymentTerms || t("Payment Terms"),
    dueDate: prev.dueDate || t("Due Date"),
    poNumber: prev.poNumber || t("PO Number"),
    item: prev.item || t("Item"),
    quantity: prev.quantity || t("Quantity"),
    rate: prev.rate || t("Rate"),
    amount: prev.amount || t("Amount"),
    notes: prev.notes || t("Notes"),
    terms: prev.terms || t("Terms"),
    subtotal: prev.subtotal || t("Subtotal"),
    tax: prev.tax || t("Tax"),
    discount: prev.discount || t("Discount"),
    shipping: prev.shipping || t("Shipping"),
    total: prev.total || t("Total"),
    amountPaid: prev.amountPaid || t("Amount Paid"),
    balanceDue: prev.balanceDue || t("Balance Due"),
  }));

  setiLabels((prev) => ({
    item: prev.item || t("Item"),
    quantity: prev.quantity || t("Quantity"),
    rate: prev.rate || t("Rate"),
    amount: prev.amount || t("Amount"),
    notes: prev.notes || t("Notes"),
    terms: prev.terms || t("Terms"),
    subtotal: prev.subtotal || t("Subtotal"),
    tax: prev.tax || t("Tax"),
    discount: prev.discount || t("Discount"),
    shipping: prev.shipping || t("Shipping"),
    total: prev.total || t("Total"),
    amountPaid: prev.amountPaid || t("Amount Paid"),
    balanceDue: prev.balanceDue || t("Balance Due"),
    from: prev.from || t("From"),
    billTo: prev.billTo || t("Bill To"),
    shipTo: prev.shipTo || t("Ship To"),
    paymentTerms: prev.paymentTerms || t("Payment Terms"),
    dueDate: prev.dueDate || t("Due Date"),
    poNumber: prev.poNumber || t("PO Number"),
    currency: prev.currency || t("Currency"),
  }));
}, [i18n.language]);
